import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Shared/Nav";
import React from "react";
import { ReduxProvider } from "@/store/ReduxProvider";
import AuthProvider from "@/Firebase/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ReduxProvider>
          <AuthProvider>
            <header>
              <Nav />
            </header>
            <main>{children}</main>
            <footer></footer>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
